# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - binary: protoc-gen-swagger
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
